version: "3.9"

services:
  user-service:
    build: ./user-service

  product-service:
    build: ./product-service

  krakend:
    image: devopsfaith/krakend
    ports:
      - "8082:8080"

    volumes:
      - ./krakend:/etc/krakend

    command:
      - run
      - -c
      - /etc/krakend/krakend.json

    depends_on:
      - user-service
      - product-service
